repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        language: python
        types: [file, python]

-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [file, python]

-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest --driver Chrome --driver-path chromedriver
        language: system
        pass_filenames: false
        always_run: true
