[tool.poetry]
name = "selenium-testing-library"
version = "0.0.1"
description = ""
authors = ["Anže Pečar <anze@pecar.me>"]

[tool.poetry.dependencies]
python = "^3.7"
selenium = "^3.0.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.5b0"
pytest-selenium = "^2.0.1"
pytest-watch = "^4.2.0"
mypy = "^0.812"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
