# This workflow will install pip-tools, run pip-compile to update all dependencies and then
# open a PR unless everything is up to date.

name: Upgrade dependencies

on:
  schedule:
  - cron: "0 6 1 * 6"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Run pip-compile
      run: |
        poetry update
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@4
      with:
        commit-message: Update dependencies
        branch: bot/update_dependencies
        delete-branch: true
        title: 'Update dependencies'
        body: |
          New updates for project dependencies 🚀
        reviewers: anze3db
